context:
  version: "0.1.10"
  python_min: "3.12"

package:
  name: dyno
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dyno.py/archive/v${{ version }}.tar.gz
  sha256: 8ac5996960ef8be3765efe29ecb26526892d32352cb89d576f4f0430b8757926

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:

  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip

  run:
    - python >=${{ python_min }}
    - altair >=6.0.0,<7
    - interegular >=0.3.3,<0.4
    - lark >=1.3.1,<2
    - numpy >=2.4.2,<3
    - pandas >=3.0.0,<4
    - plotly >=6.5.2,<7
    - pyyaml >=6.0,<7
    - rich >=14.3.2,<15
    - scipy >=1.17.0,<2
    - sympy >=1.14.0,<2
    - tempita >=0.6.0,<0.7
    - typing_extensions >=4.15.0,<5
    - dynare-preprocessor-pylib
    - vega_datasets

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - dyno
        
about:
  homepage: https://github.com/EconForge/dyno.py
  summary: A simple library for solving dynamic stochastic economic models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albop
